import os
from pathlib import Path

import boto3

# Root folder of vendor-payments-streaming-pipeline.
# Can be overridden via environment variable.
PROJECT3_ROOT = Path(
    os.getenv("PROJECT3_ROOT", r"E:\dev\vendor-payments-streaming-pipeline")
)

# Root folder of vendor-payments-airflow-orchestration output.
# Can be overridden via environment variable.
PROJECT4_OUTPUT_ROOT = Path(
    os.getenv("PROJECT4_OUTPUT_ROOT", r"E:\dev\vendor-payments-airflow-orchestration\output")
)

# S3 destination settings. Bucket must be provided before running.
S3_BUCKET = os.getenv("S3_BUCKET", "your-s3-bucket-name")
S3_PREFIX = os.getenv("S3_PREFIX", "data-platform/vendor-payments")

# Local streaming outputs generated by Project 3.
STREAMING_STAGING_FILE = (
    PROJECT3_ROOT
    / "output"
    / "staging"
    / "vendor_payments_streaming_staging.jsonl"
)

STREAMING_CURATED_CSV_FILE = (
    Path("data")
    / "streaming"
    / "curated"
    / "vendor_payments_streaming_events.csv"
)

STREAMING_SUMMARY_REPORT = (
    PROJECT3_ROOT
    / "output"
    / "reports"
    / "streaming_summary_report.json"
)

# Local orchestration summary generated by Project 4.
AIRFLOW_ORCHESTRATION_SUMMARY = (
    PROJECT4_OUTPUT_ROOT
    / "reports"
    / "airflow_orchestration_summary.json"
)


def build_upload_plan() -> list[tuple[Path, str]]:
    """Build local-to-S3 upload mapping for validated streaming outputs."""
    return [
        (
            STREAMING_STAGING_FILE,
            f"{S3_PREFIX}/streaming/staging/{STREAMING_STAGING_FILE.name}",
        ),
        (
            STREAMING_CURATED_CSV_FILE,
            f"{S3_PREFIX}/streaming/curated/{STREAMING_CURATED_CSV_FILE.name}",
        ),
        (
            STREAMING_SUMMARY_REPORT,
            f"{S3_PREFIX}/streaming/reports/{STREAMING_SUMMARY_REPORT.name}",
        ),
        (
            AIRFLOW_ORCHESTRATION_SUMMARY,
            f"{S3_PREFIX}/streaming/reports/{AIRFLOW_ORCHESTRATION_SUMMARY.name}",
        ),
    ]


def validate_upload_plan(upload_plan: list[tuple[Path, str]]) -> None:
    """Validate that all planned local files exist before uploading."""
    missing_files = [local_path for local_path, _ in upload_plan if not local_path.exists()]

    if missing_files:
        missing_list = "\n".join(str(path) for path in missing_files)
        raise FileNotFoundError(f"Missing required files:\n{missing_list}")


def upload_files_to_s3(upload_plan: list[tuple[Path, str]]) -> None:
    """Upload all files in the upload plan to S3."""
    s3_client = boto3.client("s3")

    for local_path, s3_key in upload_plan:
        print(f"Uploading {local_path}")
        print(f"-> s3://{S3_BUCKET}/{s3_key}")

        s3_client.upload_file(
            Filename=str(local_path),
            Bucket=S3_BUCKET,
            Key=s3_key,
        )

    print("Streaming upload completed successfully.")


def main() -> None:
    if S3_BUCKET == "your-s3-bucket-name":
        raise ValueError(
            "Please set S3_BUCKET environment variable before running this script."
        )

    upload_plan = build_upload_plan()
    validate_upload_plan(upload_plan)

    print("Vendor Payments streaming cloud upload plan:")
    for local_path, s3_key in upload_plan:
        print(f"- {local_path.name} -> s3://{S3_BUCKET}/{s3_key}")

    upload_files_to_s3(upload_plan)


if __name__ == "__main__":
    main()