import os
from pathlib import Path

import boto3

# Root folder of vendor-payments-etl-analytics. Can be overridden via environment variable.
PROJECT1_ROOT = Path(os.getenv("PROJECT1_ROOT", r"E:\dev\vendor-payments-etl-analytics"))

# S3 destination settings. Bucket must be provided before running.
S3_BUCKET = os.getenv("S3_BUCKET", "your-s3-bucket-name")
S3_PREFIX = os.getenv("S3_PREFIX", "data-platform/vendor-payments")

# Local sample outputs generated by the vendor-payments-etl-analytics pipeline.
RAW_SAMPLE_FILE = PROJECT1_ROOT / "data" / "sample" / "vendor_payments_sample.csv"
SILVER_SAMPLE_FILE = (
    PROJECT1_ROOT
    / "data"
    / "processed"
    / "silver"
    / "vendor_payments_silver_sample.csv"
)
GOLD_SAMPLE_DIR = PROJECT1_ROOT / "data" / "processed" / "gold_sample"
REPORTS_DIR = PROJECT1_ROOT / "reports"


def build_upload_plan() -> list[tuple[Path, str]]:
    """Build local-to-S3 upload mapping for Vendor Payments sample outputs."""
    upload_plan: list[tuple[Path, str]] = [
        (
            RAW_SAMPLE_FILE,
            f"{S3_PREFIX}/raw/sample/{RAW_SAMPLE_FILE.name}",
        ),
        (
            SILVER_SAMPLE_FILE,
            f"{S3_PREFIX}/silver/sample/{SILVER_SAMPLE_FILE.name}",
        ),
    ]

    for file_path in sorted(GOLD_SAMPLE_DIR.glob("*.csv")):
        upload_plan.append(
            (
                file_path,
                f"{S3_PREFIX}/gold/sample/{file_path.name}",
            )
        )

    for file_path in sorted(REPORTS_DIR.glob("*.txt")):
        upload_plan.append(
            (
                file_path,
                f"{S3_PREFIX}/reports/sample/{file_path.name}",
            )
        )

    return upload_plan


def validate_upload_plan(upload_plan: list[tuple[Path, str]]) -> None:
    """Validate that all planned local files exist before uploading."""
    missing_files = [local_path for local_path, _ in upload_plan if not local_path.exists()]

    if missing_files:
        missing_list = "\n".join(str(path) for path in missing_files)
        raise FileNotFoundError(f"Missing required files:\n{missing_list}")


def upload_files_to_s3(upload_plan: list[tuple[Path, str]]) -> None:
    """Upload all files in the upload plan to S3."""
    s3_client = boto3.client("s3")

    for local_path, s3_key in upload_plan:
        print(f"Uploading {local_path}")
        print(f"-> s3://{S3_BUCKET}/{s3_key}")

        s3_client.upload_file(
            Filename=str(local_path),
            Bucket=S3_BUCKET,
            Key=s3_key,
        )

    print("Upload completed successfully.")


def main() -> None:
    if S3_BUCKET == "your-s3-bucket-name":
        raise ValueError(
            "Please set S3_BUCKET environment variable before running this script."
        )

    upload_plan = build_upload_plan()
    validate_upload_plan(upload_plan)

    print("Vendor Payments cloud upload plan:")
    for local_path, s3_key in upload_plan:
        print(f"- {local_path.name} -> s3://{S3_BUCKET}/{s3_key}")

    upload_files_to_s3(upload_plan)


if __name__ == "__main__":
    main()