CREATE EXTERNAL TABLE IF NOT EXISTS vendor_payments_analytics.vendor_payments_streaming_events (
  business_composite_key string,
  dedup_status string,
  department string,
  department_name string,
  event_id string,
  event_timestamp string,
  event_type string,
  fiscal_year string,
  ingested_at string,
  payload_business_composite_key string,
  payload_character string,
  payload_character_code string,
  payload_contract_number string,
  payload_contract_title string,
  payload_data_as_of string,
  payload_data_loaded_at string,
  payload_department string,
  payload_department_code string,
  payload_department_norm string,
  payload_encumbrance_balance string,
  payload_event_id string,
  payload_event_timestamp string,
  payload_event_type string,
  payload_fiscal_year string,
  payload_fund string,
  payload_fund_category string,
  payload_fund_category_code string,
  payload_fund_category_norm string,
  payload_fund_code string,
  payload_fund_type string,
  payload_fund_type_code string,
  payload_is_fiscal_year_mismatch string,
  payload_is_large_paid_100m string,
  payload_is_large_paid_10m string,
  payload_is_large_paid_1b string,
  payload_is_large_paid_1m string,
  payload_is_missing_department string,
  payload_is_missing_purchase_order_date string,
  payload_is_negative_paid string,
  payload_is_non_profit string,
  payload_non_profit_indicator string,
  payload_object string,
  payload_object_code string,
  payload_organization_group string,
  payload_organization_group_code string,
  payload_po_month string,
  payload_po_year string,
  payload_program string,
  payload_program_code string,
  payload_purchase_order string,
  payload_purchase_order_date string,
  payload_purchasing_authority_description string,
  payload_related_govt_units string,
  payload_source_row_hash string,
  payload_source_system string,
  payload_sub_object string,
  payload_sub_object_code string,
  payload_supplier_name string,
  payload_supplier_name_norm string,
  payload_vouchers_paid string,
  payload_vouchers_pending string,
  payload_vouchers_pending_retainage string,
  payment_amount string,
  payment_status string,
  source_row_hash string,
  source_system string,
  supplier_name string,
  vendor_name string,
  vouchers_paid string
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
  'separatorChar' = ',',
  'quoteChar' = '"',
  'escapeChar' = '\\'
)
STORED AS TEXTFILE
LOCATION 's3://vendor-payments-data-platform-thana/data-platform/vendor-payments/streaming/curated/'
TBLPROPERTIES (
  'skip.header.line.count' = '1'
);